# rHideTags by Rey
# Updated by zoga-com & mrElken
#
# Features:
# Minecraft formatting & HEX color formatting
# PlaceholderAPI support

actionbar: true
actionbar_message: '$name'

chat: true
chat_message: '$name'
