name: rHideTags
version: ${project.version}
main: ru.elken.Rey_rHideTags.Main
api-version: 1.20
authors: [Rey, zoga-com, mrElken]
description: Plugin to hide players nametags
softdepend: [PlaceholderAPI]
commands:
  rht:
    description: rHideTags command
    usage: /rht <params>
    permission: rhidetags.command
  rhidetags:
    description: rHideTags command
    usage: /rhidetags <params>
    permission: rhidetags.command
permissions:
  rhidetags.command:
    description: Allow to use plugin commands
    default: op
  rhidetags.reload:
    description: Use /rhidetags reload
    default: op